import type { Metadata } from 'next';

import { bebas, lato, oswald } from './font';
import './globals.css';

export const metadata: Metadata = {
  title: 'Landing Page | CT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} ${lato.variable} ${oswald.variable}`}>
        {children}
      </body>
    </html>
  );
}
